### ISSUE TITLE
NPE when running on sbt

### ISSUE THREAD

**Issue by cquiroz** [functional-streams-for-scala/fs2#1115]
I did a small library to generate code using `http4s` and `cats-effect` and it works fine standalone. However when I execute it as part of sbt it produces a strange `NPE`:

```
[error] java.lang.NullPointerException
[error] 	at fs2.internal.Algebra$.$anonfun$compileLoop$1(Algebra.scala:233)
[error] 	at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:167)
[error] 	at cats.effect.IO.unsafeRunTimed(IO.scala:304)
[error] 	at cats.effect.IO.unsafeRunSync(IO.scala:239)
[error] 	at $c9cd8ea8c3740374a25e$.generateMimeDB(build.sbt:18)
[error] 	at $c9cd8ea8c3740374a25e$.$anonfun$core$5(build.sbt:34)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
```

This starts with a call to 
https://github.com/cquiroz/mime-http4s-generator/blob/master/src/main/scala/mimegenerator/MimeGenerator.scala#L177

It's very odd to me why the NPE only happens when running inside `sbt`. When called standalone it works fine

This is happening with `fs2` version 0.10.3 and `cats-effect` 0.10.0

**Comment by cquiroz** [comment]
This was due to mixing `App` into the application. Moral of the story, don't use `App` or confine it to the top level call

Thanks @mpilquist
