### ISSUE TITLE
support Scala 2.13

### ISSUE THREAD

**Issue by xuwei-k** [functional-streams-for-scala/fs2#1232]
https://github.com/scala/bug/issues/11030#issuecomment-414581637 😢

**Comment by mpilquist** [comment]
Thanks for tackling that and finding this issue!

**Comment by SethTisue** [comment]
in the 2.13 community build, fs2's dependencies are now green

and at e.g. https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1607/ we see:

```
[fs2] Processing subproject: coreJVM
[fs2] [error] **** Missing dependency: the library org.scala-lang.modules#scala-parallel-collections is not provided (in space "scala.main") by any project in this configuration file.
[fs2] [error] In order to control which version is used, please add the corresponding project to the build file
[fs2] [error] (or use "check-missing:false" to ignore (not recommended)).
[fs2] [error] java.lang.RuntimeException: Required dependency not found
[fs2] [error] 	at scala.sys.package$.error(package.scala:26)
[fs2] [error] 	at com.typesafe.dbuild.plugin.DBuildRunner$.$anonfun$fixModule$8(DBuildRunner.scala:205)
[fs2] [error] 	at scala.Option.getOrElse(Option.scala:121)
```

unfortunately scala-parallel-collections won't be landing for M5 before Christmas.

fs2's dependency on scala-parallel-collections is test-only and appears to be razor-thin:

```
% git grep collection.parallel
core/jvm/src/test/scala/fs2/HashSpec.scala:    val vec = collection.parallel.immutable.ParVector.fill(100)(s)
```

I would strongly suggest just commenting that out or removing it so that work on M5 support can proceed.

**Comment by mpilquist** [comment]
I would not have guessed fs2 depended on parallel collections. I’ll take a look in a hour or two.

**Comment by mpilquist** [comment]
Fix in https://github.com/functional-streams-for-scala/fs2/pull/1346

**Comment by SethTisue** [comment]
thanks, looks like that should help.

before you can proceed further you'll need cats-effect to publish, they have added an M5 cross build but haven't actually published yet (see https://github.com/typelevel/cats-effect/issues/66)

over in the community build, we don't have to wait for publishing since everything is built from source. trying it at https://github.com/scala/community-builds/pull/817

**Comment by SethTisue** [comment]
the community build is now hitting a compile error: https://github.com/scala/community-builds/pull/817#issuecomment-443069710

likely the fs2 code just needs some updating for the new collections? hard to be sure at a glance

**Comment by mpilquist** [comment]
Try 010d1aef1c6c9ec9c8d015b78fb11df826b62c89 for a fix to Chunk.scala error
-- I don't think it's related to collections but rather inference?

The error in Pull.scala looks squarely like a compiler bug.

**Comment by SethTisue** [comment]
@mpilquist can I ask you to open a bug on it at https://github.com/scala/bug ? I'm going on vacation soon until January

**Comment by mpilquist** [comment]
@SethTisue Sure, is it okay if it isn't minimized? Instead just a link to the failed community build? I can try to minimize but not in the next couple of days most likely.

**Comment by SethTisue** [comment]
hmm.... better to wait until it's minimized, I guess

**Comment by mpilquist** [comment]
BTW, I opened https://github.com/scala/bug/issues/11303

**Comment by mpilquist** [comment]
Fixed by #1378

**Comment by kaishh** [comment]
@mpilquist Any plans for a maven central release for 2.13.0-M5? We're planning to migrate our codebase to 2.13 as soon as our dependencies are available and fs2 & http4s are the finish line as of now.

**Comment by mpilquist** [comment]
@kaishh Yeah, hoping to get a release out soon - version 1.0.2. There are a few PRs I'd like to get merged first that are waiting on review.

**Comment by mpilquist** [comment]
Sorry, make that 1.0.3

**Comment by SethTisue** [comment]
scala/make-release-notes@ce1405156436af5c87506b07af4bf9507f776126
