### ISSUE TITLE
Support for graalvm native image 

### ISSUE THREAD

**Issue by janstenpickle** [functional-streams-for-scala/fs2#1237]
Hi guys, loving the work! I was wondering if anyone had managed to build a graalvm native image with a dependency on fs2. It seems to have a bit of a problem with the `Algebra` 

```
warning: unknown locality of class Lfs2/internal/Algebra$R$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$R$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$Done$3;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$Done$3; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$Out$3;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$Out$3; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$Interrupted$3;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$Interrupted$3; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$OpenInterruptibly$3;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$OpenInterruptibly$3; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$Done$4$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$Done$4$; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$Interrupted$4$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$Interrupted$4$; which is not following the naming convention.
[
warning: unknown locality of class Lfs2/internal/Algebra$OpenInterruptibly$4$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$OpenInterruptibly$4$; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$Out$4$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$Out$4$; which is not following the naming convention.
```

It seems there are similar issues with Kotlin https://github.com/oracle/graal/issues/374 ObjectScanner https://github.com/oracle/graal/issues/372. 

I'm happy to help out in any way I can in trying to get this working.

**Comment by janstenpickle** [comment]
So I moved those classes out of the the `compileLoop` method and it seems to have resolved the compilation issues and build me a binary. I'm having problems running, however that's almost certainly not a problem with fs2. 

Although, like you say, the compilation issues a likely a problem with the byte code the Scala compiler outputs. I'll see if I can raise an issue with those guys regarding this.

**Comment by mpilquist** [comment]
Sounds good. Feel free to put a PR together for moving the classes out of `compileLoop` method.

**Comment by mpilquist** [comment]
What version of fs2 and cats-effect are you using?

**Comment by janstenpickle** [comment]
Fs2 is from the latest 1.0-series branch, so it's a 1.0.0-SNAPSHOT build and cats-effect is 1.0.0-RC3.

I'm going to see if I can make a `Timer` instance for `IO` which works with substratevm in a bit.

**Comment by pchlupacek** [comment]
Also, the CompileLoop may be extracted as own class, instead being wrapped in function, that may perhaps solve the issues.

**Comment by janstenpickle** [comment]
So it turns out I was building against a cached version of fs2 without my changes having been made. I have no idea how it managed to compile at one as I never changed any of the arguments to `native-image` and now, after a fresh build of the fat jar, I have more errors than before (not just from fs2).

I'm going to go back to the drawing board and make some simple nested classes in a project with no dependencies and see how it behaves.

**Comment by janstenpickle** [comment]
So it seems the problem stems from lack of support for [InvokeDynamic](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md#invokedynamic-bytecode-and-method-handles) in SubstrateVM, so it's definitely not an issue with fs2.

I'll probably follow up with the Scala team to see if there's anyway to work around the limitation, but I don't hold out much hope.

**Comment by janstenpickle** [comment]
I'm going to close this issue as it seems less to do with fs2 and more to do with graal/scala playing together nicely. If I remember I'll post back here if I manage to get my project working, but upon further investigation I was also getting similar errors from a Circe macro which could be the cause of the problem as described [in this blog post](https://medium.com/graalvm/compiling-scala-faster-with-graalvm-86c5c0857fa3).

**Comment by tovbinm** [comment]
I am completely lost on how to troubleshoot this as I am getting a similar error:
```
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$State$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$State$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$Uninitialized$1$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$Uninitialized$1$; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$Done$2$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$Done$2$; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$R$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$R$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$Done$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$Done$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$Interrupted$2$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$Interrupted$2$; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$Interrupted$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$Interrupted$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$OnSubscribe$2$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$OnSubscribe$2$; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$Input$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$Input$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$OnSubscribe$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$OnSubscribe$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$OnNext$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$OnNext$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$OnComplete$1$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$OnComplete$1$; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$OnError$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$OnError$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$OnFinalize$1$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$OnFinalize$1$; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$OnDequeue$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$OnDequeue$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$WaitingOnUpstream$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$WaitingOnUpstream$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$UpstreamError$2$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$UpstreamError$2$; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$Idle$2$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$Idle$2$; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$UpstreamError$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$UpstreamError$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$DownstreamCancellation$1$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$DownstreamCancellation$1$; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$Idle$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$Idle$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$RequestBeforeSubscription$2$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$RequestBeforeSubscription$2$; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$RequestBeforeSubscription$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$RequestBeforeSubscription$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$WaitingOnUpstream$2$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$WaitingOnUpstream$2$; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$UpstreamCompletion$1$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$UpstreamCompletion$1$; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$OnDequeue$2$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$OnDequeue$2$; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$Out$1;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$Out$1; which is not following the naming convention.
warning: unknown locality of class Lfs2/internal/Algebra$Out$2$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/internal/Algebra$Out$2$; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$OnError$2$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$OnError$2$; which is not following the naming convention.
warning: unknown locality of class Lfs2/interop/reactivestreams/StreamSubscriber$OnNext$2$;, assuming class is not local. To remove the warning report an issue to the library or language author. The issue is caused by Lfs2/interop/reactivestreams/StreamSubscriber$OnNext$2$; which is not following the naming convention.

Fatal error: java.lang.reflect.MalformedParameterizedTypeException
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(ConstructorRepository.java:94)
	at java.lang.reflect.Executable.getGenericParameterTypes(Executable.java:283)
	at java.lang.reflect.Method.getGenericParameterTypes(Method.java:283)
	at com.oracle.svm.reflect.hosted.ReflectionMetadataFeature.replacer(ReflectionMetadataFeature.java:65)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:532)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:136)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:107)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:100)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:75)
	at com.oracle.graal.pointsto.ObjectScanner.scanField(ObjectScanner.java:175)
	at com.oracle.graal.pointsto.ObjectScanner.doScan(ObjectScanner.java:344)
	at com.oracle.graal.pointsto.ObjectScanner.access$400(ObjectScanner.java:62)
	at com.oracle.graal.pointsto.ObjectScanner$3$1.run(ObjectScanner.java:414)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1447)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1225)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1187)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1146)
```

**Comment by tovbinm** [comment]
Somehow the Scala style classes are not being treated correctly here. Perhaps @cstancu can recommend something?

**Comment by tovbinm** [comment]
@jastenpickle any recommendations?

**Comment by tovbinm** [comment]
@janstenpickle any recommendations?

**Comment by janstenpickle** [comment]
@tovbinm I gave up on trying to get this to work quite some time ago, sorry! It looks like graal doesn't like scala's generated class names.

**Comment by tovbinm** [comment]
That's bizarre! How come any other Scala library works with GraalVM AOT compiler considering that all inner trait/classes in Scala have `$` in their names?

**Comment by djspiewak** [comment]
@tovbinm @janstenpickle A bit of hunting indicates that this is a pretty common error from the native-image packer, and it tends to be masking some other more specific error. Given the class names in question here, I'm guessing it's actually a use of `invokedynamic` which native-image isn't recognizing as a lambda call site.

Basically, the substrate vm only supports *restricted* `invokedynamic` usage, solely as sufficient to support Java 8's lambda encoding. Scala mirrors that encoding pretty closely, but there are some differences, and I'm guessing those differences are what is confusing the analyzer.

Theoretically, native-image really *should* support this kind of thing. I would raise the bug with them.

**Comment by tovbinm** [comment]
Thank you @djspiewak
