### ISSUE TITLE
2.2.0 NoSuchMethodError

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1747]
```scala
object Test extends App {
  println(Stream(1, 2, 3).through(_.map(_ + 1)).toList)
}
```
Compile above with 2.1.0 and run with 2.2.0 and you get:
```scala
java.lang.NoSuchMethodError: fs2.Stream.fs2$Stream$$free()Lfs2/internal/FreeC;
	at Test$.$anonfun$new$1$adapted(Test.scala:5)
	at fs2.Stream$.through$extension(Stream.scala:2709)
```

First brought up by @amesgen on Gitter as it impacted http4s.

**Comment by kubukoz** [comment]
This also surfaced in doobie:

```scala
[E] java.lang.NoSuchMethodError: fs2.Stream.fs2$Stream$$free()Lfs2/internal/FreeC;
[E] 	at doobie.util.transactor$Transactor$$anon$6.apply(transactor.scala:175)
[E] 	at doobie.syntax.StreamOps.transact(stream.scala:16)
```

Looks OK on current master.
