### ISSUE TITLE
Mysterious thread "hangs" in master

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#396]
We've been seeing a lot of this lately, running against master:

```
29-May-2015 06:21:10	"pool-2-thread-3" #55 daemon prio=5 os_prio=0 tid=0x0000000020a5e800 nid=0x576 runnable [0x00002b7d354c4000]
29-May-2015 06:21:10	   java.lang.Thread.State: RUNNABLE
29-May-2015 06:21:10	        at scalaz.stream.Process$Append.flatMap(Process.scala:615)
29-May-2015 06:21:10	        at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:46)
29-May-2015 06:21:10	        at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:46)
29-May-2015 06:21:10	        at scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
29-May-2015 06:21:10	        at scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
29-May-2015 06:21:10	        at scalaz.Free.resume(Free.scala:73)
29-May-2015 06:21:10	        at scalaz.Free.go2$1(Free.scala:118)
29-May-2015 06:21:10	        at scalaz.Free.go(Free.scala:122)
29-May-2015 06:21:10	        at scalaz.Free.run(Free.scala:172)
29-May-2015 06:21:10	        at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:82)
29-May-2015 06:21:10	        at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:82)
29-May-2015 06:21:10	        at scalaz.stream.Util$.Try(Util.scala:38)
29-May-2015 06:21:10	        at scalaz.stream.Process$class.go$1(Process.scala:82)
29-May-2015 06:21:10	        at scalaz.stream.Process$class.step(Process.scala:95)
29-May-2015 06:21:10	        at scalaz.stream.Process$Append.step(Process.scala:615)
29-May-2015 06:21:10	        at scalaz.stream.Process$class.go$3(Process.scala:468)
29-May-2015 06:21:10	        at scalaz.stream.Process$$anonfun$go$3$2.apply(Process.scala:473)
29-May-2015 06:21:10	        at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:36)
29-May-2015 06:21:10	        at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:36)
29-May-2015 06:21:10	        at scalaz.concurrent.Task$.Try(Task.scala:385)
29-May-2015 06:21:10	        at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:36)
29-May-2015 06:21:10	        at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:34)
29-May-2015 06:21:10	        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
29-May-2015 06:21:10	        at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:59)
29-May-2015 06:21:10	        at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:59)
29-May-2015 06:21:10	        at scalaz.concurrent.Future.step(Future.scala:110)
29-May-2015 06:21:10	        at scalaz.concurrent.Future.listen(Future.scala:76)
29-May-2015 06:21:10	        at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
29-May-2015 06:21:10	        at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:80)
29-May-2015 06:21:10	        at scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
29-May-2015 06:21:10	        at scalaz.Free$$anonfun$map$1.apply(Free.scala:52)
29-May-2015 06:21:10	        at scalaz.Free.resume(Free.scala:73)
29-May-2015 06:21:10	        at scalaz.Free.go2$1(Free.scala:118)
29-May-2015 06:21:10	        at scalaz.Free.go(Free.scala:122)
29-May-2015 06:21:10	        at scalaz.Free.run(Free.scala:172)
29-May-2015 06:21:10	        at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:363)
29-May-2015 06:21:10	        at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:363)
29-May-2015 06:21:10	        at scalaz.stream.async.mutable.Queue$$anonfun$scalaz$stream$async$mutable$Queue$$signalClosed$1$1$$anonfun$apply$1.apply$mcV$sp(Queue.scala:170)
29-May-2015 06:21:10	        at scalaz.stream.async.mutable.Queue$$anonfun$scalaz$stream$async$mutable$Queue$$signalClosed$1$1$$anonfun$apply$1.apply(Queue.scala:170)
29-May-2015 06:21:10	        at scalaz.stream.async.mutable.Queue$$anonfun$scalaz$stream$async$mutable$Queue$$signalClosed$1$1$$anonfun$apply$1.apply(Queue.scala:170)
29-May-2015 06:21:10	        at scalaz.concurrent.StrategysLow$$anon$3$$anon$4.call(Strategy.scala:79)
29-May-2015 06:21:10	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
29-May-2015 06:21:10	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
29-May-2015 06:21:10	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
29-May-2015 06:21:10	        at java.lang.Thread.run(Thread.java:745)
```

The commonality seems to be the `signalClosed` method in `Queue`, which is throwing a `Terminated(End)` into a `Task.async` context.  I'm concerned that we were supposed to be converting this into a `Halt` somewhere, and now we aren't.  Investigation is in progress…

**Comment by djspiewak** [comment]
We have strong, but not definitive, evidence that this is being caused by something in master.  "Downgrading" to 0.7.1 resolved the issue.

**Comment by kareblak** [comment]
@djspiewak Did you ever find this one out?

**Comment by pchiusano** [comment]
I'm closing this along with any other pre 0.9 issues as wontfix.
