### ISSUE TITLE
intermittent TimeSpec failure

### ISSUE THREAD

**Issue by SethTisue** [functional-streams-for-scala/fs2#867]
seen at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/1496/consoleFull

```
[fs2] [info] TimeSpec:
[fs2] [info] time
[fs2] [info] - duration *** FAILED *** (230 milliseconds)
[fs2] [info]   java.lang.IllegalStateException: Timer already cancelled.
[fs2] [info]   at java.util.Timer.sched(Timer.java:397)
[fs2] [info]   at java.util.Timer.schedule(Timer.java:193)
[fs2] [info]   at org.scalatest.Timer.schedule(JavaClassesWrappers.scala:93)
[fs2] [info]   at org.scalatest.enablers.Timed$$anon$3.timeoutAfter(Timed.scala:335)
[fs2] [info]   at org.scalatest.enablers.Timed$$anon$3.timeoutAfter(Timed.scala:286)
[fs2] [info]   at org.scalatest.concurrent.TimeLimits.failAfterImpl(TimeLimits.scala:239)
[fs2] [info]   at org.scalatest.concurrent.TimeLimits.failAfterImpl$(TimeLimits.scala:233)
[fs2] [info]   at fs2.AsyncFs2Spec.failAfterImpl(Fs2Spec.scala:14)
[fs2] [info]   at org.scalatest.concurrent.TimeLimits.failAfter(TimeLimits.scala:230)
[fs2] [info]   at org.scalatest.concurrent.TimeLimits.failAfter$(TimeLimits.scala:229)
[fs2] [info]   at fs2.AsyncFs2Spec.failAfter(Fs2Spec.scala:14)
[fs2] [info]   at org.scalatest.concurrent.AsyncTimeLimitedTests.withFixture(AsyncTimeLimitedTests.scala:99)
[fs2] [info]   at org.scalatest.concurrent.AsyncTimeLimitedTests.withFixture$(AsyncTimeLimitedTests.scala:97)
[fs2] [info]   at fs2.AsyncFs2Spec.withFixture(Fs2Spec.scala:14)
[fs2] [info]   at org.scalatest.AsyncFreeSpecLike.invokeWithAsyncFixture$1(AsyncFreeSpecLike.scala:406)
[fs2] [info]   at org.scalatest.AsyncFreeSpecLike.$anonfun$runTest$1(AsyncFreeSpecLike.scala:419)
[fs2] [info]   at org.scalatest.AsyncSuperEngine.runTestImpl(AsyncEngine.scala:292)
[fs2] [info]   at org.scalatest.AsyncFreeSpecLike.runTest(AsyncFreeSpecLike.scala:419)
[fs2] [info]   at org.scalatest.AsyncFreeSpecLike.runTest$(AsyncFreeSpecLike.scala:400)
[fs2] [info]   at fs2.AsyncFs2Spec.fs2$Fs2SpecLike$$super$runTest(Fs2Spec.scala:14)
[fs2] [info]   at fs2.Fs2SpecLike.runTest(Fs2Spec.scala:29)
[fs2] [info]   at fs2.Fs2SpecLike.runTest$(Fs2Spec.scala:27)
[fs2] [info]   at fs2.AsyncFs2Spec.runTest(Fs2Spec.scala:14)
[fs2] [info]   at org.scalatest.AsyncFreeSpecLike.$anonfun$runTests$1(AsyncFreeSpecLike.scala:478)
[fs2] [info]   at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:434)
[fs2] [info]   at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[fs2] [info]   at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[fs2] [info]   at scala.collection.immutable.List.foldLeft(List.scala:86)
[fs2] [info]   at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:419)
[fs2] [info]   at org.scalatest.AsyncSuperEngine.runTestsInBranch(AsyncEngine.scala:475)
[fs2] [info]   at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:460)
[fs2] [info]   at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
[fs2] [info]   at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
[fs2] [info]   at scala.collection.immutable.List.foldLeft(List.scala:86)
[fs2] [info]   at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:419)
[fs2] [info]   at org.scalatest.AsyncSuperEngine.runTestsInBranch(AsyncEngine.scala:483)
[fs2] [info]   at org.scalatest.AsyncSuperEngine.runTestsImpl(AsyncEngine.scala:550)
[fs2] [info]   at org.scalatest.AsyncFreeSpecLike.runTests(AsyncFreeSpecLike.scala:478)
[fs2] [info]   at org.scalatest.AsyncFreeSpecLike.runTests$(AsyncFreeSpecLike.scala:477)
[fs2] [info]   at org.scalatest.AsyncFreeSpec.runTests(AsyncFreeSpec.scala:2278)
[fs2] [info]   at org.scalatest.Suite.run(Suite.scala:1147)
[fs2] [info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[fs2] [info]   at org.scalatest.AsyncFreeSpec.org$scalatest$AsyncFreeSpecLike$$super$run(AsyncFreeSpec.scala:2278)
[fs2] [info]   at org.scalatest.AsyncFreeSpecLike.$anonfun$run$1(AsyncFreeSpecLike.scala:522)
[fs2] [info]   at org.scalatest.AsyncSuperEngine.runImpl(AsyncEngine.scala:620)
[fs2] [info]   at org.scalatest.AsyncFreeSpecLike.run(AsyncFreeSpecLike.scala:522)
[fs2] [info]   at org.scalatest.AsyncFreeSpecLike.run$(AsyncFreeSpecLike.scala:521)
[fs2] [info]   at org.scalatest.AsyncFreeSpec.run(AsyncFreeSpec.scala:2278)
[fs2] [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[fs2] [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[fs2] [info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[fs2] [info]   at sbt.TestRunner.run(TestFramework.scala:85)
[fs2] [info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[fs2] [info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[fs2] [info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[fs2] [info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[fs2] [info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[fs2] [info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[fs2] [info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[fs2] [info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[fs2] [info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[fs2] [info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[fs2] [info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[fs2] [info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[fs2] [info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[fs2] [info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[fs2] [info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[fs2] [info]   at sbt.Execute.work(Execute.scala:237)
[fs2] [info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[fs2] [info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[fs2] [info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[fs2] [info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[fs2] [info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[fs2] [info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[fs2] [info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[fs2] [info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[fs2] [info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[fs2] [info]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by mpilquist** [comment]
I think this is caused by https://github.com/scalatest/scalatest/issues/1147. I'm waiting on advice from @bvenners on how to get a version of ScalaTest that has this fix. The 3.2.0-SNAP7 build has the fix but results on a few hundred compile errors due to changes in GeneratorDrivenPropertyChecks.
